### ISSUE TITLE
Add support for context variables for server connection properties

### ISSUE THREAD

**Issue by julienboulay** [Ekito/talend-cmis-components#11]
When the server connection properties are set with context variables, the dialog box can not be opened.

**Comment by tdaget** [comment]
May need to manage this like in t<databasetype>Input component when we ask it to show datas from database

**Comment by julienboulay** [comment]
The following behavior is implemented, if context variables are used in the connection parameters:
- when only one default context is available, this context is selected without prompt
- when multiple context are available, a context selection dialog appear before the type definition dialog. The user can select the context and the cmis session can then be opened
